name: Build & Release UniORM Binaries

on:
  push:
    tags:
      - 'v*.*.*' # e.g., v0.1.0
  workflow_dispatch: {}

permissions:
  contents: write # needed to create/upload release assets

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-linux:
    name: linux binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      # Build only Linux runtimes
      - run: npx pkg . --targets node18-linux-x64,node18-linux-arm64
      - run: ls -la dist

      # Upload artifacts when run manually (no tag)
      - name: Upload build artifacts
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: actions/upload-artifact@v4
        with:
          name: linux-binaries-${{ github.run_id }}
          path: dist/*

      # Upload to Release only when running on a tag
      - name: Upload to GitHub Release
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos:
    name: macOS binaries
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      # Build only macOS runtimes
      - run: npx pkg . --targets node18-macos-x64,node18-macos-arm64
      - run: ls -la dist

      - name: Upload build artifacts
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: actions/upload-artifact@v4
        with:
          name: macos-binaries-${{ github.run_id }}
          path: dist/*

      - name: Upload to GitHub Release
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    name: windows binaries
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      # Build only Windows runtime
      - run: npx pkg . --targets node18-win-x64
      - run: Get-ChildItem dist

      - name: Upload build artifacts
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: actions/upload-artifact@v4
        with:
          name: windows-binaries-${{ github.run_id }}
          path: dist\*

      - name: Upload to GitHub Release
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: softprops/action-gh-release@v2
        with:
          files: dist\*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
